# Generated by Django 3.0.7 on 2020-06-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
